### ISSUE TITLE
Wrong link in Bayes Rules! setup guide

### ISSUE THREAD

**Issue by alexjj** [bayes-rules/bayesrules#79]
Hello,

On https://www.bayesrulesbook.com/index.html#setup it still references `mdogucu/bayes-rules-r-package`. 

I couldn't find the repo for the book's source, as the link at the top takes me to https://github.com/ajohns24/bayes_rules which doesn't exist. So I'm just adding the issue here.

Thanks for sharing.

**Comment by mdogucu** [comment]
Thank you for bringing this to our attention. It is now fixed.
