### ISSUE TITLE
Misleading formulation of "variability" in the exercise 3.1b

### ISSUE THREAD

**Issue by RaibekTussupbekov** [bayes-rules/bayesrules#87]
First of all, thank you very much for this titanic work you've done!

> Exercise 3.1 (Tune your Beta prior: Take I) In each situation below, tune a Beta(α,β) model that accurately reflects the given prior information. In many cases, there’s no single “right” answer, but rather multiple “reasonable” answers. 
> b. A scientist has created a new test for a rare disease. They expect that the test is accurate 80% of the time with a variance of 0.05.

I suspect that "a variance of 0.05" actually means "a variability of 0.05" that consequently is the standard deviation or SD(pi) but not Var(pi). 
I made this conclusion trying to simulate beta distribution in R with Var(pi) close to 0.05. That leads to beta extremely close to 1.
On the other hand, with "a variance of 0.05" treated as SD(pi) I found reasonable values of alpha and beta, 48 and 12 respectively.

**Comment by ajohns24** [comment]
Thanks for reading the book so carefully! "variance" not "variability" is the intended word here.
