### ISSUE TITLE
Typo in 5.2.3 Gamma prior: two gamma parameters are mistakenly swapped 

### ISSUE THREAD

**Issue by RaibekTussupbekov** [bayes-rules/bayesrules#88]
[In this chapter](https://www.bayesrulesbook.com/chapter-5.html#gamma-poisson-conjugate-family) 
s = 10 and r = 2 are mistakenly swapped in the Gamma pdf formula.

Best regards

**Comment by ajohns24** [comment]
Thanks for catching this! It's now fixed.
