### ISSUE TITLE
Interception coefficient doesn't match the figure 9.2

### ISSUE THREAD

**Issue by RaibekTussupbekov** [bayes-rules/bayesrules#89]
[https://www.bayesrulesbook.com/chapter-9.html#fig:ch-9-hypothetical](https://www.bayesrulesbook.com/chapter-9.html#fig:ch-9-hypothetical)
In the chapter [9.1.1 Specifying the data model](https://www.bayesrulesbook.com/chapter-9.html#specifying-the-data-model) it's said that 

> For example, the model lines in Figure 9.2 both have intercept β0=−2000 and slope β1=100.

However, [the figure 9.2](https://www.bayesrulesbook.com/chapter-9.html#fig:ch-9-hypothetical) shows that the line intersects the y axis above zero, so it doesn't match  β0=−2000.

**Comment by ajohns24** [comment]
Thanks for reaching out @RaibekTussupbekov. The intercept is indeed -2000. The plot does not extend all the way to the y-axis, which I think is the source of confusion here. That is, if you went down to a temperature of 0, the line would cross at -2000 riders.

**Comment by RaibekTussupbekov** [comment]
> Thanks for reaching out @RaibekTussupbekov. The intercept is indeed -2000. The plot does not extend all the way to the y-axis, which I think is the source of confusion here. That is, if you went down to a temperature of 0, the line would cross at -2000 riders.
Oops, I see it now:) Thank you very much for the fantastic work you've done!
